### PR TITLE
Hot reloading

### PR DESCRIPTION
**Pull request by marcinkornek**
Added hot-reloading

### CODE REVIEW

**Comment by liorbrauer** [comment]
Awesome, been wanting to test this out for a while! :+1:

**Comment by liorbrauer** [comment]
Just wanted to update that I tested it and it works perfectly! :) this is an amazing boost to productivity

**Comment by marcinkornek** [comment]
I thought about this solution but I wasn't sure if it's a good idea to change base config everytime we run hot-dev server so I modified config file. But you are right, that your solution makes less changes and is less 'magical' :). I think that we should also add some global variables (sth like `__DEVELOPMENT__`) depending on environment (dev, production). It can be useful for example when you want to use Redux devtools only in development and disable it in production.

**Comment by mxaly** [comment]
@marcinkornek let's split env related stuff into separate issue/PR :)

**Comment by marcinkornek** [comment]
Ok but what about dev server ? now afer adding partial with react assets it would return error message that no assets are on `localhost:8080/assets` - so maybe we can change both development servers to use `webpack-dev-server`?

```js
const WebpackNotifierPlugin = require('webpack-notifier');
const config = require('./../webpack.config');

config.plugins.push(new WebpackNotifierPlugin());
config.devtool = 'eval-source-map';
config.output.publicPath = 'http://localhost:8080/assets/'
config.entry.main.push(
  'webpack-dev-server/client?http://localhost:8080'
)

module.exports = config;
```

and

```js
var config = require('./dev.config');

var jsxLoader = config.module.loaders.filter(function(loader) { return loader.key == 'jsx' })[0]
jsxLoader.loaders.unshift('react-hot');
config.entry.main.push(
  'webpack/hot/only-dev-server',
)

module.exports = config;
```

**Comment by marcinkornek** [comment]
Moved discussion about variables/feature flags to https://github.com/netguru/react_webpack_rails/issues/18

**Comment by mxaly** [comment]
As i said before - we can have standard page reload done with rails, no need webpack for that. Having react_bundle served by sprockets we can have our standard, non hot-reload development closer to production env which nice in my opinion. 

You are right about error but i think that when someone will choose not to use hot-reload, there will be no partial added to layout and no error :)

**Comment by mxaly** [comment]
@marcinkornek thanks! great work :)

**Pull request merged**
